### ISSUE TITLE
Outdated SQL-2019 and SQL-2022 download link.

### ISSUE THREAD

**Issue by fredrikbuo** [shurick81/ms-365-vms#5]
ms-365-vms\infrastructure\images\sql2019-media.ps1
`                xRemoteFile SQLServerCUFilePresent
                {
                    Uri             = "https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5023049-x64.exe"
                    DestinationPath = "C:\Install\SQLUpdates\SQLServer2019-KB5024276-x64.exe"
                    MatchSource     = $false
                }`

The Uri link does not work. I've tested with newer version and it's working.

`                    Uri             = "https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5024276-x64.exe"`

ms-365-vms\infrastructure\images\sql2022-media.ps1
Same here but for SQL 2022
`                {
                    Uri             = "https://download.microsoft.com/download/9/6/8/96819b0c-c8fb-4b44-91b5-c97015bbda9f/SQLServer2022-KB5023127-x64.exe"
                    DestinationPath = "C:\Install\SQLUpdates\SQLServer2022-KB5023127-x64.exe"
                    MatchSource     = $false
                }`

The Uri link does not work. I've tested with newer version and it's working.

`                   Uri             = "https://download.microsoft.com/download/9/6/8/96819b0c-c8fb-4b44-91b5-c97015bbda9f/SQLServer2022-KB5024396-x64.exe"`

**Comment by shurick81** [comment]
Thanks @fredrikbuo for bringing this up! Finishing last tests in https://github.com/shurick81/ms-365-vms/tree/feature/5-outdated-sql-2019-and-sql-2022-download-link. Soon will be merged to the main branch.
